apiVersion: v1
kind: Service
metadata:
  name: nullfield-demo
  namespace: nullfield
  labels:
    app.kubernetes.io/name: nullfield-demo
spec:
  selector:
    app: nullfield-demo
  ports:
    - name: proxy
      port: 9090
      targetPort: proxy
      protocol: TCP
    - name: admin
      port: 9091
      targetPort: admin
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nullfield
  namespace: nullfield
  labels:
    app.kubernetes.io/name: nullfield
