{{/*
  Reusable sidecar container snippet.
  Include it in your Deployment pod spec:

    containers:
      - name: your-app
        ...
      {{- include "nullfield.sidecar" . | nindent 6 }}
*/}}
{{- define "nullfield.sidecar" -}}
- name: nullfield
  image: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}"
  imagePullPolicy: {{ .Values.sidecar.image.pullPolicy }}
  ports:
    - name: proxy
      containerPort: {{ .Values.sidecar.listenPort }}
      protocol: TCP
    - name: admin
      containerPort: {{ .Values.sidecar.adminPort }}
      protocol: TCP
  env:
    - name: NULLFIELD_LISTEN_ADDR
      value: ":{{ .Values.sidecar.listenPort }}"
    - name: NULLFIELD_ADMIN_ADDR
      value: ":{{ .Values.sidecar.adminPort }}"
    {{- if .Values.controller.enabled }}
    - name: NULLFIELD_CONTROLLER_ADDR
      value: "{{ include "nullfield.fullname" . }}-controller.{{ .Release.Namespace }}:{{ .Values.controller.grpcPort }}"
    {{- end }}
  envFrom:
    - configMapRef:
        name: {{ .Release.Name }}-nullfield
  livenessProbe:
    httpGet:
      path: /healthz
      port: admin
    initialDelaySeconds: 3
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: admin
    initialDelaySeconds: 2
    periodSeconds: 5
  resources:
    {{- toYaml .Values.sidecar.resources | nindent 4 }}
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
{{- end }}
