// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: controller.proto

package controllerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NullfieldController_CheckBudget_FullMethodName     = "/nullfield.v1alpha1.NullfieldController/CheckBudget"
	NullfieldController_CreateHold_FullMethodName      = "/nullfield.v1alpha1.NullfieldController/CreateHold"
	NullfieldController_ReportEvent_FullMethodName     = "/nullfield.v1alpha1.NullfieldController/ReportEvent"
	NullfieldController_RegisterSidecar_FullMethodName = "/nullfield.v1alpha1.NullfieldController/RegisterSidecar"
)

// NullfieldControllerClient is the client API for NullfieldController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NullfieldControllerClient interface {
	// CheckBudget verifies whether the caller has remaining budget.
	// Sidecars call this before forwarding budgeted tool calls.
	CheckBudget(ctx context.Context, in *CheckBudgetRequest, opts ...grpc.CallOption) (*CheckBudgetResponse, error)
	// CreateHold parks a tool call for human approval.
	// Sidecars call this when a HOLD rule matches and block until resolved.
	CreateHold(ctx context.Context, in *CreateHoldRequest, opts ...grpc.CallOption) (*CreateHoldResponse, error)
	// ReportEvent sends an audit event to the controller for alerting.
	// Fire-and-forget — sidecars do not block on the response.
	ReportEvent(ctx context.Context, in *ReportEventRequest, opts ...grpc.CallOption) (*ReportEventResponse, error)
	// RegisterSidecar announces a sidecar to the controller on startup.
	RegisterSidecar(ctx context.Context, in *RegisterSidecarRequest, opts ...grpc.CallOption) (*RegisterSidecarResponse, error)
}

type nullfieldControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewNullfieldControllerClient(cc grpc.ClientConnInterface) NullfieldControllerClient {
	return &nullfieldControllerClient{cc}
}

func (c *nullfieldControllerClient) CheckBudget(ctx context.Context, in *CheckBudgetRequest, opts ...grpc.CallOption) (*CheckBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBudgetResponse)
	err := c.cc.Invoke(ctx, NullfieldController_CheckBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nullfieldControllerClient) CreateHold(ctx context.Context, in *CreateHoldRequest, opts ...grpc.CallOption) (*CreateHoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHoldResponse)
	err := c.cc.Invoke(ctx, NullfieldController_CreateHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nullfieldControllerClient) ReportEvent(ctx context.Context, in *ReportEventRequest, opts ...grpc.CallOption) (*ReportEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportEventResponse)
	err := c.cc.Invoke(ctx, NullfieldController_ReportEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nullfieldControllerClient) RegisterSidecar(ctx context.Context, in *RegisterSidecarRequest, opts ...grpc.CallOption) (*RegisterSidecarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSidecarResponse)
	err := c.cc.Invoke(ctx, NullfieldController_RegisterSidecar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NullfieldControllerServer is the server API for NullfieldController service.
// All implementations must embed UnimplementedNullfieldControllerServer
// for forward compatibility.
type NullfieldControllerServer interface {
	// CheckBudget verifies whether the caller has remaining budget.
	// Sidecars call this before forwarding budgeted tool calls.
	CheckBudget(context.Context, *CheckBudgetRequest) (*CheckBudgetResponse, error)
	// CreateHold parks a tool call for human approval.
	// Sidecars call this when a HOLD rule matches and block until resolved.
	CreateHold(context.Context, *CreateHoldRequest) (*CreateHoldResponse, error)
	// ReportEvent sends an audit event to the controller for alerting.
	// Fire-and-forget — sidecars do not block on the response.
	ReportEvent(context.Context, *ReportEventRequest) (*ReportEventResponse, error)
	// RegisterSidecar announces a sidecar to the controller on startup.
	RegisterSidecar(context.Context, *RegisterSidecarRequest) (*RegisterSidecarResponse, error)
	mustEmbedUnimplementedNullfieldControllerServer()
}

// UnimplementedNullfieldControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNullfieldControllerServer struct{}

func (UnimplementedNullfieldControllerServer) CheckBudget(context.Context, *CheckBudgetRequest) (*CheckBudgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBudget not implemented")
}
func (UnimplementedNullfieldControllerServer) CreateHold(context.Context, *CreateHoldRequest) (*CreateHoldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHold not implemented")
}
func (UnimplementedNullfieldControllerServer) ReportEvent(context.Context, *ReportEventRequest) (*ReportEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportEvent not implemented")
}
func (UnimplementedNullfieldControllerServer) RegisterSidecar(context.Context, *RegisterSidecarRequest) (*RegisterSidecarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSidecar not implemented")
}
func (UnimplementedNullfieldControllerServer) mustEmbedUnimplementedNullfieldControllerServer() {}
func (UnimplementedNullfieldControllerServer) testEmbeddedByValue()                             {}

// UnsafeNullfieldControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NullfieldControllerServer will
// result in compilation errors.
type UnsafeNullfieldControllerServer interface {
	mustEmbedUnimplementedNullfieldControllerServer()
}

func RegisterNullfieldControllerServer(s grpc.ServiceRegistrar, srv NullfieldControllerServer) {
	// If the following call panics, it indicates UnimplementedNullfieldControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NullfieldController_ServiceDesc, srv)
}

func _NullfieldController_CheckBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NullfieldControllerServer).CheckBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NullfieldController_CheckBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NullfieldControllerServer).CheckBudget(ctx, req.(*CheckBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NullfieldController_CreateHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NullfieldControllerServer).CreateHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NullfieldController_CreateHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NullfieldControllerServer).CreateHold(ctx, req.(*CreateHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NullfieldController_ReportEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NullfieldControllerServer).ReportEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NullfieldController_ReportEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NullfieldControllerServer).ReportEvent(ctx, req.(*ReportEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NullfieldController_RegisterSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSidecarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NullfieldControllerServer).RegisterSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NullfieldController_RegisterSidecar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NullfieldControllerServer).RegisterSidecar(ctx, req.(*RegisterSidecarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NullfieldController_ServiceDesc is the grpc.ServiceDesc for NullfieldController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NullfieldController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nullfield.v1alpha1.NullfieldController",
	HandlerType: (*NullfieldControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckBudget",
			Handler:    _NullfieldController_CheckBudget_Handler,
		},
		{
			MethodName: "CreateHold",
			Handler:    _NullfieldController_CreateHold_Handler,
		},
		{
			MethodName: "ReportEvent",
			Handler:    _NullfieldController_ReportEvent_Handler,
		},
		{
			MethodName: "RegisterSidecar",
			Handler:    _NullfieldController_RegisterSidecar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}
