// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: controller.proto

package controllerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Tool          string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	Tokens        int64                  `protobuf:"varint,4,opt,name=tokens,proto3" json:"tokens,omitempty"` // estimated tokens for this call (0 if unknown)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBudgetRequest) Reset() {
	*x = CheckBudgetRequest{}
	mi := &file_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBudgetRequest) ProtoMessage() {}

func (x *CheckBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBudgetRequest.ProtoReflect.Descriptor instead.
func (*CheckBudgetRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{0}
}

func (x *CheckBudgetRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *CheckBudgetRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CheckBudgetRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *CheckBudgetRequest) GetTokens() int64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

type CheckBudgetResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Allowed         bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // populated when denied
	RemainingCalls  int64                  `protobuf:"varint,3,opt,name=remaining_calls,json=remainingCalls,proto3" json:"remaining_calls,omitempty"`
	RemainingTokens int64                  `protobuf:"varint,4,opt,name=remaining_tokens,json=remainingTokens,proto3" json:"remaining_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckBudgetResponse) Reset() {
	*x = CheckBudgetResponse{}
	mi := &file_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBudgetResponse) ProtoMessage() {}

func (x *CheckBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBudgetResponse.ProtoReflect.Descriptor instead.
func (*CheckBudgetResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{1}
}

func (x *CheckBudgetResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckBudgetResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckBudgetResponse) GetRemainingCalls() int64 {
	if x != nil {
		return x.RemainingCalls
	}
	return 0
}

func (x *CheckBudgetResponse) GetRemainingTokens() int64 {
	if x != nil {
		return x.RemainingTokens
	}
	return 0
}

type CreateHoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Timeout       string                 `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`                      // duration string, e.g. "5m"
	OnTimeout     string                 `protobuf:"bytes,6,opt,name=on_timeout,json=onTimeout,proto3" json:"on_timeout,omitempty"` // "DENY" or "ALLOW"
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`                      // original JSON-RPC request body
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHoldRequest) Reset() {
	*x = CreateHoldRequest{}
	mi := &file_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHoldRequest) ProtoMessage() {}

func (x *CreateHoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHoldRequest.ProtoReflect.Descriptor instead.
func (*CreateHoldRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHoldRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *CreateHoldRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *CreateHoldRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateHoldRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateHoldRequest) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *CreateHoldRequest) GetOnTimeout() string {
	if x != nil {
		return x.OnTimeout
	}
	return ""
}

func (x *CreateHoldRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateHoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldId        string                 `protobuf:"bytes,1,opt,name=hold_id,json=holdId,proto3" json:"hold_id,omitempty"`
	Decision      string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"` // "approved", "denied", "timeout"
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHoldResponse) Reset() {
	*x = CreateHoldResponse{}
	mi := &file_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHoldResponse) ProtoMessage() {}

func (x *CreateHoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHoldResponse.ProtoReflect.Descriptor instead.
func (*CreateHoldResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{3}
}

func (x *CreateHoldResponse) GetHoldId() string {
	if x != nil {
		return x.HoldId
	}
	return ""
}

func (x *CreateHoldResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *CreateHoldResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReportEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // e.g. "tool.denied", "anomaly.velocity"
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Tool          string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	Identity      string                 `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Target        string                 `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"` // which target namespace/deployment
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Gate          string                 `protobuf:"bytes,9,opt,name=gate,proto3" json:"gate,omitempty"`                                                                                // enforcement gate: registry, policy, budget, hold, etc.
	ReasonClass   string                 `protobuf:"bytes,10,opt,name=reason_class,json=reasonClass,proto3" json:"reason_class,omitempty"`                                              // low-cardinality class for metrics/alerts
	RuleIndex     *int32                 `protobuf:"varint,11,opt,name=rule_index,json=ruleIndex,proto3,oneof" json:"rule_index,omitempty"`                                             // zero-based index in the active policy
	RuleId        string                 `protobuf:"bytes,12,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`                                                             // stable rule id from policy YAML/CRD
	PolicyRef     string                 `protobuf:"bytes,13,opt,name=policy_ref,json=policyRef,proto3" json:"policy_ref,omitempty"`                                                    // policy name/hash/reference
	RegistryRef   string                 `protobuf:"bytes,14,opt,name=registry_ref,json=registryRef,proto3" json:"registry_ref,omitempty"`                                              // registry name/hash/reference
	Route         string                 `protobuf:"bytes,15,opt,name=route,proto3" json:"route,omitempty"`                                                                             // gateway route, when applicable
	Labels        map[string]string      `protobuf:"bytes,16,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // bounded operator-defined audit labels
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEventRequest) Reset() {
	*x = ReportEventRequest{}
	mi := &file_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventRequest) ProtoMessage() {}

func (x *ReportEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventRequest.ProtoReflect.Descriptor instead.
func (*ReportEventRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{4}
}

func (x *ReportEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ReportEventRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ReportEventRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ReportEventRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ReportEventRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReportEventRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReportEventRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ReportEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ReportEventRequest) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *ReportEventRequest) GetReasonClass() string {
	if x != nil {
		return x.ReasonClass
	}
	return ""
}

func (x *ReportEventRequest) GetRuleIndex() int32 {
	if x != nil && x.RuleIndex != nil {
		return *x.RuleIndex
	}
	return 0
}

func (x *ReportEventRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *ReportEventRequest) GetPolicyRef() string {
	if x != nil {
		return x.PolicyRef
	}
	return ""
}

func (x *ReportEventRequest) GetRegistryRef() string {
	if x != nil {
		return x.RegistryRef
	}
	return ""
}

func (x *ReportEventRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *ReportEventRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ReportEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEventResponse) Reset() {
	*x = ReportEventResponse{}
	mi := &file_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventResponse) ProtoMessage() {}

func (x *ReportEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventResponse.ProtoReflect.Descriptor instead.
func (*ReportEventResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{5}
}

type RegisterSidecarRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetName      string                 `protobuf:"bytes,1,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`                // e.g. "brain-gateway"
	TargetNamespace string                 `protobuf:"bytes,2,opt,name=target_namespace,json=targetNamespace,proto3" json:"target_namespace,omitempty"` // e.g. "camazotz"
	PodName         string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Version         string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`                       // nullfield version
	ToolCount       int32                  `protobuf:"varint,5,opt,name=tool_count,json=toolCount,proto3" json:"tool_count,omitempty"` // number of registered tools
	RuleCount       int32                  `protobuf:"varint,6,opt,name=rule_count,json=ruleCount,proto3" json:"rule_count,omitempty"` // number of policy rules
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterSidecarRequest) Reset() {
	*x = RegisterSidecarRequest{}
	mi := &file_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSidecarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSidecarRequest) ProtoMessage() {}

func (x *RegisterSidecarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSidecarRequest.ProtoReflect.Descriptor instead.
func (*RegisterSidecarRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterSidecarRequest) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *RegisterSidecarRequest) GetTargetNamespace() string {
	if x != nil {
		return x.TargetNamespace
	}
	return ""
}

func (x *RegisterSidecarRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *RegisterSidecarRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterSidecarRequest) GetToolCount() int32 {
	if x != nil {
		return x.ToolCount
	}
	return 0
}

func (x *RegisterSidecarRequest) GetRuleCount() int32 {
	if x != nil {
		return x.RuleCount
	}
	return 0
}

type RegisterSidecarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSidecarResponse) Reset() {
	*x = RegisterSidecarResponse{}
	mi := &file_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSidecarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSidecarResponse) ProtoMessage() {}

func (x *RegisterSidecarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSidecarResponse.ProtoReflect.Descriptor instead.
func (*RegisterSidecarResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterSidecarResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterSidecarResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_controller_proto protoreflect.FileDescriptor

const file_controller_proto_rawDesc = "" +
	"\n" +
	"\x10controller.proto\x12\x12nullfield.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"{\n" +
	"\x12CheckBudgetRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x12\x16\n" +
	"\x06tokens\x18\x04 \x01(\x03R\x06tokens\"\x9b\x01\n" +
	"\x13CheckBudgetResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12'\n" +
	"\x0fremaining_calls\x18\x03 \x01(\x03R\x0eremainingCalls\x12)\n" +
	"\x10remaining_tokens\x18\x04 \x01(\x03R\x0fremainingTokens\"\xcd\x01\n" +
	"\x11CreateHoldRequest\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\tR\atimeout\x12\x1d\n" +
	"\n" +
	"on_timeout\x18\x06 \x01(\tR\tonTimeout\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"a\n" +
	"\x12CreateHoldResponse\x12\x17\n" +
	"\ahold_id\x18\x01 \x01(\tR\x06holdId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xe6\x04\n" +
	"\x12ReportEventRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x12\x1a\n" +
	"\bidentity\x18\x04 \x01(\tR\bidentity\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x16\n" +
	"\x06target\x18\a \x01(\tR\x06target\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04gate\x18\t \x01(\tR\x04gate\x12!\n" +
	"\freason_class\x18\n" +
	" \x01(\tR\vreasonClass\x12\"\n" +
	"\n" +
	"rule_index\x18\v \x01(\x05H\x00R\truleIndex\x88\x01\x01\x12\x17\n" +
	"\arule_id\x18\f \x01(\tR\x06ruleId\x12\x1d\n" +
	"\n" +
	"policy_ref\x18\r \x01(\tR\tpolicyRef\x12!\n" +
	"\fregistry_ref\x18\x0e \x01(\tR\vregistryRef\x12\x14\n" +
	"\x05route\x18\x0f \x01(\tR\x05route\x12J\n" +
	"\x06labels\x18\x10 \x03(\v22.nullfield.v1alpha1.ReportEventRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_rule_index\"\x15\n" +
	"\x13ReportEventResponse\"\xd7\x01\n" +
	"\x16RegisterSidecarRequest\x12\x1f\n" +
	"\vtarget_name\x18\x01 \x01(\tR\n" +
	"targetName\x12)\n" +
	"\x10target_namespace\x18\x02 \x01(\tR\x0ftargetNamespace\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"tool_count\x18\x05 \x01(\x05R\ttoolCount\x12\x1d\n" +
	"\n" +
	"rule_count\x18\x06 \x01(\x05R\truleCount\"O\n" +
	"\x17RegisterSidecarResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9e\x03\n" +
	"\x13NullfieldController\x12^\n" +
	"\vCheckBudget\x12&.nullfield.v1alpha1.CheckBudgetRequest\x1a'.nullfield.v1alpha1.CheckBudgetResponse\x12[\n" +
	"\n" +
	"CreateHold\x12%.nullfield.v1alpha1.CreateHoldRequest\x1a&.nullfield.v1alpha1.CreateHoldResponse\x12^\n" +
	"\vReportEvent\x12&.nullfield.v1alpha1.ReportEventRequest\x1a'.nullfield.v1alpha1.ReportEventResponse\x12j\n" +
	"\x0fRegisterSidecar\x12*.nullfield.v1alpha1.RegisterSidecarRequest\x1a+.nullfield.v1alpha1.RegisterSidecarResponseB9Z7github.com/babywyrm/nullfield/api/v1alpha1/controllerpbb\x06proto3"

var (
	file_controller_proto_rawDescOnce sync.Once
	file_controller_proto_rawDescData []byte
)

func file_controller_proto_rawDescGZIP() []byte {
	file_controller_proto_rawDescOnce.Do(func() {
		file_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)))
	})
	return file_controller_proto_rawDescData
}

var file_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_controller_proto_goTypes = []any{
	(*CheckBudgetRequest)(nil),      // 0: nullfield.v1alpha1.CheckBudgetRequest
	(*CheckBudgetResponse)(nil),     // 1: nullfield.v1alpha1.CheckBudgetResponse
	(*CreateHoldRequest)(nil),       // 2: nullfield.v1alpha1.CreateHoldRequest
	(*CreateHoldResponse)(nil),      // 3: nullfield.v1alpha1.CreateHoldResponse
	(*ReportEventRequest)(nil),      // 4: nullfield.v1alpha1.ReportEventRequest
	(*ReportEventResponse)(nil),     // 5: nullfield.v1alpha1.ReportEventResponse
	(*RegisterSidecarRequest)(nil),  // 6: nullfield.v1alpha1.RegisterSidecarRequest
	(*RegisterSidecarResponse)(nil), // 7: nullfield.v1alpha1.RegisterSidecarResponse
	nil,                             // 8: nullfield.v1alpha1.ReportEventRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_controller_proto_depIdxs = []int32{
	9, // 0: nullfield.v1alpha1.ReportEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	8, // 1: nullfield.v1alpha1.ReportEventRequest.labels:type_name -> nullfield.v1alpha1.ReportEventRequest.LabelsEntry
	0, // 2: nullfield.v1alpha1.NullfieldController.CheckBudget:input_type -> nullfield.v1alpha1.CheckBudgetRequest
	2, // 3: nullfield.v1alpha1.NullfieldController.CreateHold:input_type -> nullfield.v1alpha1.CreateHoldRequest
	4, // 4: nullfield.v1alpha1.NullfieldController.ReportEvent:input_type -> nullfield.v1alpha1.ReportEventRequest
	6, // 5: nullfield.v1alpha1.NullfieldController.RegisterSidecar:input_type -> nullfield.v1alpha1.RegisterSidecarRequest
	1, // 6: nullfield.v1alpha1.NullfieldController.CheckBudget:output_type -> nullfield.v1alpha1.CheckBudgetResponse
	3, // 7: nullfield.v1alpha1.NullfieldController.CreateHold:output_type -> nullfield.v1alpha1.CreateHoldResponse
	5, // 8: nullfield.v1alpha1.NullfieldController.ReportEvent:output_type -> nullfield.v1alpha1.ReportEventResponse
	7, // 9: nullfield.v1alpha1.NullfieldController.RegisterSidecar:output_type -> nullfield.v1alpha1.RegisterSidecarResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_controller_proto_init() }
func file_controller_proto_init() {
	if File_controller_proto != nil {
		return
	}
	file_controller_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_proto_goTypes,
		DependencyIndexes: file_controller_proto_depIdxs,
		MessageInfos:      file_controller_proto_msgTypes,
	}.Build()
	File_controller_proto = out.File
	file_controller_proto_goTypes = nil
	file_controller_proto_depIdxs = nil
}
